--- #YAML:1.0
name: WWW-Shorten
version: 1.5.6
license: perl
distribution_type: module
requires:
  LWP: 5.69
  LWP::UserAgent: 2.001
  URI: 1.23
  perl: 5.6.0
recommends: {}
build_requires:
  Test::More: 0.47
  Test::Pod: 0.95
  Test::Signature: 1.03
conflicts: {}
generated_by: Module::Build version 0.16
