--- #YAML:1.0
name: WWW-Shorten
version: 1.5.5
license: perl
distribution_type: module
requires:
  LWP: 5.65
  LWP::UserAgent: 2.001
  URI: 1.22
  WWW::Mechanize: 0.31
  perl: 5.6.0
recommends: {}
build_requires:
  Test::More: 0.47
  Test::Signature: 1.02
conflicts: {}
generated_by: Module::Build version 0.14
