--- #YAML:1.0
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: Module::Build version 0.11
license: perl
name: WWW-Shorten
recommends: {}
requires:
  LWP: 5.65
  LWP::UserAgent: 2.001
  URI: 1.22
  WWW::Mechanize: 0.31
  perl: 5.6.0
version: 1.5.0
