--- #YAML:1.0
distribution_type: module
name: WWW-Shorten
version: 1.91
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  File::Find::Rule: 0.10
  Test::Pod: 0.95
requires:
  URI: 1.23
  LWP::UserAgent: 2.003
  LWP: 5.69

private:
  directory:
    - t

provides:
  WWW::Shorten:
    file: lib/WWW/Shorten.pm
    version: 1.81
  WWW::Shorten::EkDk:
    file: lib/WWW/Shorten/EkDk.pm
    version: 1.81
  WWW::Shorten::MakeAShorterLink:
    file: lib/WWW/Shorten/MakeAShorterLink.pm
    version: 1.81
  WWW::Shorten::Metamark:
    file: lib/WWW/Shorten/Metamark.pm
    version: 1.81
  WWW::Shorten::NotLong:
    file: lib/WWW/Shorten/NotLong.pm
    version: 1.81
  WWW::Shorten::Shorl:
    file: lib/WWW/Shorten/Shorl.pm
    version: 1.81
  WWW::Shorten::SmLnk:
    file: lib/WWW/Shorten/SmLnk.pm
    version: 1.81
  WWW::Shorten::SnipURL:
    file: lib/WWW/Shorten/SnipURL.pm
    version: 1.81
  WWW::Shorten::TinyClick:
    file: lib/WWW/Shorten/TinyClick.pm
    version: 1.81
  WWW::Shorten::TinyURL:
    file: lib/WWW/Shorten/TinyURL.pm
    version: 1.81
  WWW::Shorten::generic:
    file: lib/WWW/Shorten/generic.pm
    version: 1.81

generated_by: docmaker version 0.89
