--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
distribution_type: module
name: WWW-Shorten
date: 8 Sep 2003
author: SPOON
version: 1.87
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  File::Find::Rule: 0.11
  Test::Pod: 0.95
requires:
  LWP: 5.69
  LWP::Protocol::http: 0
  LWP::UserAgent: 2.003
  URI: 1.25

private:
  directory:
    - t

provides:

dynamic_config: 0
generated_by: docmaker version 1.01
