---
name: WWW-Shorten
version: 2.00
author:
  - 'Iain Truskett <spoon@cpan.org>'
  - 'Based on WWW::MakeAShorterLink by Dave Cross <dave@mag-sol.com>'
abstract: Interface to URL shortening sites.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  LWP: 5.75
  LWP::UserAgent: 2.023
  URI: 1.27
  perl: 5.6.0
build_requires:
  Test::More: 0.47
provides:
  WWW::Shorten:
    file: lib/WWW/Shorten.pm
    version: 1.98
  WWW::Shorten::BabyURL:
    file: lib/WWW/Shorten/BabyURL.pm
    version: 1.90
  WWW::Shorten::EkDk:
    file: lib/WWW/Shorten/EkDk.pm
    version: 1.91
  WWW::Shorten::LinkToolbot:
    file: lib/WWW/Shorten/LinkToolbot.pm
    version: 1.90
  WWW::Shorten::Linkz:
    file: lib/WWW/Shorten/Linkz.pm
    version: 1.90
  WWW::Shorten::MakeAShorterLink:
    file: lib/WWW/Shorten/MakeAShorterLink.pm
    version: 1.90
  WWW::Shorten::Metamark:
    file: lib/WWW/Shorten/Metamark.pm
    version: 1.91
  WWW::Shorten::NotLong:
    file: lib/WWW/Shorten/NotLong.pm
    version: 1.90
  WWW::Shorten::OneShortLink:
    file: lib/WWW/Shorten/OneShortLink.pm
    version: 1.93
  WWW::Shorten::Shorl:
    file: lib/WWW/Shorten/Shorl.pm
    version: 1.91
  WWW::Shorten::ShortLink:
    file: lib/WWW/Shorten/ShortLink.pm
    version: 1.91
  WWW::Shorten::SmLnk:
    file: lib/WWW/Shorten/SmLnk.pm
    version: 1.91
  WWW::Shorten::SnipURL:
    file: lib/WWW/Shorten/SnipURL.pm
    version: 1.91
  WWW::Shorten::TinyClick:
    file: lib/WWW/Shorten/TinyClick.pm
    version: 1.90
  WWW::Shorten::TinyURL:
    file: lib/WWW/Shorten/TinyURL.pm
    version: 1.90
  WWW::Shorten::URLjr:
    file: lib/WWW/Shorten/URLjr.pm
    version: 1.91
  WWW::Shorten::V3:
    file: lib/WWW/Shorten/V3.pm
    version: 1.93
  WWW::Shorten::generic:
    file: lib/WWW/Shorten/generic.pm
    version: 1.92
  WWW::Shorten::qURL:
    file: lib/WWW/Shorten/qURL.pm
    version: 1.91
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
