---
abstract: 'Interface to URL shortening sites.'
author:
  - 'Original Iain Truskett <spoon@cpan.org>'
  - 'Based on WWW::MakeAShorterLink by Dave Cross <dave@mag-sol.com>'
build_requires:
  Test::More: 0.47
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten
provides:
  WWW::Shorten:
    file: lib/WWW/Shorten.pm
    version: 3.04
  WWW::Shorten::LinkToolbot:
    file: lib/WWW/Shorten/LinkToolbot.pm
    version: 1.90
  WWW::Shorten::Linkz:
    file: lib/WWW/Shorten/Linkz.pm
    version: 1.90
  WWW::Shorten::MakeAShorterLink:
    file: lib/WWW/Shorten/MakeAShorterLink.pm
    version: 1.90
  WWW::Shorten::Metamark:
    file: lib/WWW/Shorten/Metamark.pm
    version: 1.91
  WWW::Shorten::TinyClick:
    file: lib/WWW/Shorten/TinyClick.pm
    version: 1.90
  WWW::Shorten::TinyURL:
    file: lib/WWW/Shorten/TinyURL.pm
    version: 1.90
  WWW::Shorten::UserAgent:
    file: lib/WWW/Shorten/UserAgent.pm
  WWW::Shorten::generic:
    file: lib/WWW/Shorten/generic.pm
    version: 1.92
requires:
  Config::Auto: 0
  LWP: 5.75
  LWP::UserAgent: 2.023
  URI: 1.27
  perl: 5.006
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 3.04
