--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
distribution_type: module
name: WWW-Shorten
date: 13 Nov 2003
author: SPOON
version: 1.88
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  Test::Pod: 1.02
  Test::Signature: 1.05
requires:
  LWP: 5.75
  LWP::UserAgent: 2.023
  URI: 1.27

private:
  directory:
    - t

provides:
  WWW::Shorten:
    file: lib/WWW/Shorten.pm
    version: 1.88
  WWW::Shorten::_dead:
    file: lib/WWW/Shorten/_dead.pm
    version: 1.88
  WWW::Shorten::BabyURL:
    file: lib/WWW/Shorten/BabyURL.pm
    version: 1.86
  WWW::Shorten::EkDk:
    file: lib/WWW/Shorten/EkDk.pm
    version: 1.88
  WWW::Shorten::generic:
    file: lib/WWW/Shorten/generic.pm
    version: 1.81
  WWW::Shorten::Linkz:
    file: lib/WWW/Shorten/Linkz.pm
    version: 1.87
  WWW::Shorten::MakeAShorterLink:
    file: lib/WWW/Shorten/MakeAShorterLink.pm
    version: 1.81
  WWW::Shorten::Metamark:
    file: lib/WWW/Shorten/Metamark.pm
    version: 1.81
  WWW::Shorten::NotLong:
    file: lib/WWW/Shorten/NotLong.pm
    version: 1.81
  WWW::Shorten::OneShortLink:
    file: lib/WWW/Shorten/OneShortLink.pm
    version: 1.88
  WWW::Shorten::qURL:
    file: lib/WWW/Shorten/qURL.pm
    version: 1.88
  WWW::Shorten::Shorl:
    file: lib/WWW/Shorten/Shorl.pm
    version: 1.81
  WWW::Shorten::ShortLink:
    file: lib/WWW/Shorten/ShortLink.pm
    version: 1.88
  WWW::Shorten::SmLnk:
    file: lib/WWW/Shorten/SmLnk.pm
    version: 1.84
  WWW::Shorten::SnipURL:
    file: lib/WWW/Shorten/SnipURL.pm
    version: 1.81
  WWW::Shorten::TinyClick:
    file: lib/WWW/Shorten/TinyClick.pm
    version: 1.88
  WWW::Shorten::Tinylink:
    file: lib/WWW/Shorten/Tinylink.pm
    version: 1.84
  WWW::Shorten::TinyURL:
    file: lib/WWW/Shorten/TinyURL.pm
    version: 1.81
  WWW::Shorten::URLjr:
    file: lib/WWW/Shorten/URLjr.pm
    version: 1.86
  WWW::Shorten::V3:
    file: lib/WWW/Shorten/V3.pm
    version: 1.85

dynamic_config: 0
generated_by: docmaker version 1.01
